name: Bug report
description: 不具合を報告する
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ご報告ありがとうございます。再現手順をできるだけ具体的に記載してください。
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 何が起きたかを簡潔に説明してください。
      placeholder: setup.sh 実行時にエラーが発生する
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 再現手順
      description: 再現に必要な手順を順番に記載してください。
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待した挙動
      placeholder: 正常にシンボリックリンクが作成される
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 実行環境
      description: OS、シェル、利用ツールのバージョンを記載してください。
      placeholder: macOS 15.x / zsh 5.9 / Claude Code vX.Y.Z
    validations:
      required: true
