name: Feature request
description: 機能追加や改善を提案する
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        提案ありがとうございます。背景と期待する効果を詳しく教えてください。
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: 現状のどこに問題があるかを記載してください。
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 提案内容
      description: 具体的な仕様や振る舞いを記載してください。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した別案があれば記載してください。
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: 補足情報
      description: 関連リンクやスクリーンショットがあれば記載してください。
    validations:
      required: false
